# Generated by Django 2.1.2 on 2019-03-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190328_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
    ]
