# Generated by Django 2.1.2 on 2019-03-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calle',
            field=models.CharField(default='', max_length=100, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='profile',
            name='colonia',
            field=models.CharField(default='', max_length=100, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postalCode',
            field=models.IntegerField(default=0, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre Completo'),
        ),
    ]
