# Generated by Django 2.1.2 on 2019-03-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190328_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cardBack',
            field=models.IntegerField(default=0, verbose_name='CVV/CVC'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cardDate',
            field=models.DateField(null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cardName',
            field=models.CharField(default='', max_length=80, verbose_name='Nombre del Titular'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cardNumber',
            field=models.IntegerField(default=0, verbose_name='Número de Tarjeta'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cardType',
            field=models.CharField(default='', max_length=15, verbose_name='Empresa (Ej.VISA)'),
        ),
    ]
