# Generated by Django 2.1.2 on 2019-03-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190326_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Descripción'),
        ),
    ]
